### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Const-me** [SunburstApps/Win2D.WinUI#2]
Several exceptions happen in a sequence.

First two are `DllNotFoundException`, complaining about not being able to load `Microsoft.Graphics.Canvas.UI.Xaml.dll` and then `Microsoft.Graphics.Canvas.UI.dll`, the HRESULT code is `0x8007007E` in both cases.

Then in the debug output there’s one more error message:

> WinRT originate error - 0x80070490 : 'Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.'

Finally, my app gets “XAML parsing failed.” exception in `InitializeComponent` method, and fails to start up.

I have confirmed when I select “WinUI in UWP” project template, your library renders that encircled “Hello world” just fine. The bug only happens when using “WinUI in Desktop” project template.

Any workarounds?

Thanks in advance.

**Comment by wjk** [comment]
I’m afraid I cannot help debug this library, as I know as little about it as you do. I simply packaged it from someone else's project. Bugfix PRs are nevertheless welcome. Thanks!
